### ISSUE TITLE
Discussion: Make hawck-input user a system user

### ISSUE THREAD

**Issue by Esgariot** [snyball/hawck#65]
I've noticed that newly created user gets its own entry in login manager, and was wondering if creating user as system user, rather than normal one without home, is both viable and secure for use-cases that this app introduces.

**Comment by snyball** [comment]
This is definitely a bug, the `hawck-input` user should have its shell set to `/bin/nologin`, I'll be updating the install scripts to do this.

**Comment by snyball** [comment]
Should be resolved as of [4fff45c2de8115da5f51dcd5d27f55490f9ae921](https://aur.archlinux.org/cgit/aur.git/commit/?h=hawck-git&id=4fff45c2de8115da5f51dcd5d27f55490f9ae921) in the AUR and 2eded86867df31013d00b0a7b6692f7a01472bba which updates the AUR submodule in this repo.

**Comment by rbits0** [comment]
I installed this recently on KDE Neon, and this still happened to me. I assume I got the latest version, so this might not be fixed properly.

**Comment by snyball** [comment]
@rbits0 Can you post the output of `grep hawck /etc/passwd`?

**Comment by washanhanzi** [comment]
```
// grep hawck /etc/passwd
hawck-input:x:1001:1001::/var/lib/hawck-input:/bin/nologin
```

**Comment by Birthday-Cakeman** [comment]
I second this. I installed this on KDE and it created a new login user.
